{
	"_Type": "Action.Type.ODataService.ChangeSet",
	"ActionResult": {
		"_Name": "ClosePOItemSave"
	},
	"Target": {
		"Service": "/MDK_ErrorArchive/Services/SampleServiceV2.service"
	},
	"Actions": [
		"/MDK_ErrorArchive/Rules/PurchaseOrderHeaders/saveItemToLocal.js",
		"/MDK_ErrorArchive/Actions/PurchaseOrderHeaders/POHeaders_CreatePurchaseOrderItem.action"
	]
}