{
	"_Type": "Action.Type.ODataService.ChangeSet",
	"ActionResult": {
		"_Name": "CreateHeaderAndNavToCreateItems"
	},
	"Target": {
		"Service": "/MDK_ErrorArchive/Services/SampleServiceV2.service"
	},
	"Actions": [
		"/MDK_ErrorArchive/Actions/PurchaseOrderHeaders/NavToPOHeaders_CreatePurchaseOrderItem.action"
	]
}