{
	"_Type": "Action.Type.ODataService.CreateRelatedEntity",
	"ActionResult": {
		"_Name": "create"
	},
	"OnFailure": "/MDK_ErrorArchive/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/MDK_ErrorArchive/Actions/CreateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "PurchaseOrderItems",
		"Service": "/MDK_ErrorArchive/Services/SampleServiceV2.service"
	},
	"ParentLink": {
		"Target": {
			"EntitySet": "PurchaseOrderHeaders",
			"ReadLink": "pending_1"
		},
		"Property": "Items"
	},
	"Properties": {
		"CurrencyCode": "#Control:CurrencyCode/#Value",
		"GrossAmount": "#Control:GrossAmount/#Value",
		"ItemNumber": "#Control:ItemNumber/#Value",
		"NetAmount": "#Control:NetAmount/#Value",
		"ProductId": "#Control:ProductId/#SelectedValue",
		"PurchaseOrderId": "#Control:PurchaseOrderId/#SelectedValue",
		"Quantity": "#Control:Quantity/#Value",
		"QuantityUnit": "#Control:QuantityUnit/#Value",
		"TaxAmount": "#Control:TaxAmount/#Value"
	}
}