{
	"_Type": "Action.Type.ToastMessage",
	"OnSuccess": "/MDK_ErrorArchive/Actions/CloseModalPage_Complete.action",
	"Message": "Entity created",
	"Duration": 2,
	"IsIconHidden": true,
	"Animated": true
}